package org.letunov.service;

import org.letunov.domainModel.User;
import org.springframework.http.ResponseEntity;

import java.util.List;

public interface UserService
{
    public List<User> getTeachersList();
    public List<User> getStudentsList();
    public List<User> getAdminsList();
    public User createUserWithAutoGeneratedLoginAndPassword(User user);
    public String getLastAutogeneratedPassword();
    public User getAuthenticatedUser();
    User getById(long id);
    boolean isAllowDeleteUser(long id);
    ResponseEntity<Object> deleteUser(long id);
}
